public enum GameplayEventType
{
    ValveClosed,
    ValveOpened,
    WindowOpened,
    WindowClosed,
    FireIgnited,
    FireExtinguished,
    GasLeakStarted,
    GasLeakStopped,
    GasLevelChanged,
    PlayerEnteredDangerZone,
    PlayerExitedDangerZone,
    PlayerFainted,
    MatchStarted,
    MatchEnded,
    WrongActionPerformed,
    DoorOpened,
    DoorClosed
}
